/* The following code was generated by JFlex 1.6.0 */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 2006  Silvano Rivoira <silvano.rivoira@polito.it>                    *
 * All rights reserved.                                                    *
 *                                                                         *
 * This program is free software; you can redistribute it and/or modify    *
 * it under the terms of the GNU General Public License. See the file      *
 * COPYRIGHT for more information.                                         *
 *                                                                         *
 * This program is distributed in the hope that it will be useful,         *
 * but WITHOUT ANY WARRANTY;              *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* MiniJava  language lexer specification */

package jflexcup;

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>java.flex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\72\1\73\1\1\16\7\4\0\1\3\1\63"+
    "\1\15\1\0\1\6\1\71\1\66\1\16\1\50\1\51\1\5\1\14"+
    "\1\57\1\70\1\12\1\4\1\10\11\11\1\65\1\56\1\62\1\60"+
    "\1\61\1\64\1\0\4\6\1\13\25\6\1\54\1\17\1\55\1\0"+
    "\1\6\1\0\1\24\1\20\1\26\1\34\1\23\1\35\1\46\1\27"+
    "\1\36\1\6\1\45\1\22\1\47\1\25\1\21\1\40\1\6\1\30"+
    "\1\31\1\33\1\41\1\44\1\37\1\32\1\42\1\43\1\52\1\67"+
    "\1\53\1\0\6\7\1\74\32\7\2\0\4\6\4\0\1\6\2\0"+
    "\1\7\7\0\1\6\4\0\1\6\5\0\27\6\1\0\37\6\1\0"+
    "\u01ca\6\4\0\14\6\16\0\5\6\7\0\1\6\1\0\1\6\21\0"+
    "\160\7\5\6\1\0\2\6\2\0\4\6\10\0\1\6\1\0\3\6"+
    "\1\0\1\6\1\0\24\6\1\0\123\6\1\0\213\6\1\0\5\7"+
    "\2\0\236\6\11\0\46\6\2\0\1\6\7\0\47\6\11\0\55\7"+
    "\1\0\1\7\1\0\2\7\1\0\2\7\1\0\1\7\10\0\33\6"+
    "\5\0\3\6\15\0\4\7\7\0\1\6\4\0\13\7\5\0\53\6"+
    "\37\7\4\0\2\6\1\7\143\6\1\0\1\6\10\7\1\0\6\7"+
    "\2\6\2\7\1\0\4\7\2\6\12\7\3\6\2\0\1\6\17\0"+
    "\1\7\1\6\1\7\36\6\33\7\2\0\131\6\13\7\1\6\16\0"+
    "\12\7\41\6\11\7\2\6\4\0\1\6\5\0\26\6\4\7\1\6"+
    "\11\7\1\6\3\7\1\6\5\7\22\0\31\6\3\7\244\0\4\7"+
    "\66\6\3\7\1\6\22\7\1\6\7\7\12\6\2\7\2\0\12\7"+
    "\1\0\7\6\1\0\7\6\1\0\3\7\1\0\10\6\2\0\2\6"+
    "\2\0\26\6\1\0\7\6\1\0\1\6\3\0\4\6\2\0\1\7"+
    "\1\6\7\7\2\0\2\7\2\0\3\7\1\6\10\0\1\7\4\0"+
    "\2\6\1\0\3\6\2\7\2\0\12\7\4\6\7\0\1\6\5\0"+
    "\3\7\1\0\6\6\4\0\2\6\2\0\26\6\1\0\7\6\1\0"+
    "\2\6\1\0\2\6\1\0\2\6\2\0\1\7\1\0\5\7\4\0"+
    "\2\7\2\0\3\7\3\0\1\7\7\0\4\6\1\0\1\6\7\0"+
    "\14\7\3\6\1\7\13\0\3\7\1\0\11\6\1\0\3\6\1\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6"+
    "\10\7\1\0\3\7\1\0\3\7\2\0\1\6\17\0\2\6\2\7"+
    "\2\0\12\7\1\0\1\6\17\0\3\7\1\0\10\6\2\0\2\6"+
    "\2\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7"+
    "\1\6\7\7\2\0\2\7\2\0\3\7\10\0\2\7\4\0\2\6"+
    "\1\0\3\6\2\7\2\0\12\7\1\0\1\6\20\0\1\7\1\6"+
    "\1\0\6\6\3\0\3\6\1\0\4\6\3\0\2\6\1\0\1\6"+
    "\1\0\2\6\3\0\2\6\3\0\3\6\3\0\14\6\4\0\5\7"+
    "\3\0\3\7\1\0\4\7\2\0\1\6\6\0\1\7\16\0\12\7"+
    "\11\0\1\6\7\0\3\7\1\0\10\6\1\0\3\6\1\0\27\6"+
    "\1\0\12\6\1\0\5\6\3\0\1\6\7\7\1\0\3\7\1\0"+
    "\4\7\7\0\2\7\1\0\2\6\6\0\2\6\2\7\2\0\12\7"+
    "\22\0\2\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6"+
    "\1\0\5\6\2\0\1\7\1\6\7\7\1\0\3\7\1\0\4\7"+
    "\7\0\2\7\7\0\1\6\1\0\2\6\2\7\2\0\12\7\1\0"+
    "\2\6\17\0\2\7\1\0\10\6\1\0\3\6\1\0\51\6\2\0"+
    "\1\6\7\7\1\0\3\7\1\0\4\7\1\6\10\0\1\7\10\0"+
    "\2\6\2\7\2\0\12\7\12\0\6\6\2\0\2\7\1\0\22\6"+
    "\3\0\30\6\1\0\11\6\1\0\1\6\2\0\7\6\3\0\1\7"+
    "\4\0\6\7\1\0\1\7\1\0\10\7\22\0\2\7\15\0\60\6"+
    "\1\7\2\6\7\7\4\0\10\6\10\7\1\0\12\7\47\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0\4\6"+
    "\1\0\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0\2\6"+
    "\1\0\4\6\1\7\2\6\6\7\1\0\2\7\1\6\2\0\5\6"+
    "\1\0\1\6\1\0\6\7\2\0\12\7\2\0\2\6\42\0\1\6"+
    "\27\0\2\7\6\0\12\7\13\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\10\6\1\0\44\6\4\0\24\7\1\0\2\7\5\6"+
    "\13\7\1\0\44\7\11\0\1\7\71\0\53\6\24\7\1\6\12\7"+
    "\6\0\6\6\4\7\4\6\3\7\1\6\3\7\2\6\7\7\3\6"+
    "\4\7\15\6\14\7\1\6\17\7\2\0\46\6\12\0\53\6\1\0"+
    "\1\6\3\0\u0149\6\1\0\4\6\2\0\7\6\1\0\1\6\1\0"+
    "\4\6\2\0\51\6\1\0\4\6\2\0\41\6\1\0\4\6\2\0"+
    "\7\6\1\0\1\6\1\0\4\6\2\0\17\6\1\0\71\6\1\0"+
    "\4\6\2\0\103\6\2\0\3\7\40\0\20\6\20\0\125\6\14\0"+
    "\u026c\6\2\0\21\6\1\0\32\6\5\0\113\6\3\0\3\6\17\0"+
    "\15\6\1\0\4\6\3\7\13\0\22\6\3\7\13\0\22\6\2\7"+
    "\14\0\15\6\1\0\3\6\1\0\2\7\14\0\64\6\40\7\3\0"+
    "\1\6\3\0\2\6\1\7\2\0\12\7\41\0\3\7\2\0\12\7"+
    "\6\0\130\6\10\0\51\6\1\7\1\6\5\0\106\6\12\0\35\6"+
    "\3\0\14\7\4\0\14\7\12\0\12\7\36\6\2\0\5\6\13\0"+
    "\54\6\4\0\21\7\7\6\2\7\6\0\12\7\46\0\27\6\5\7"+
    "\4\0\65\6\12\7\1\0\35\7\2\0\13\7\6\0\12\7\15\0"+
    "\1\6\130\0\5\7\57\6\21\7\7\6\4\0\12\7\21\0\11\7"+
    "\14\0\3\7\36\6\12\7\3\0\2\6\12\7\6\0\46\6\16\7"+
    "\14\0\44\6\24\7\10\0\12\7\3\0\3\6\12\7\44\6\122\0"+
    "\3\7\1\0\25\7\4\6\1\7\4\6\1\7\15\0\300\6\47\7"+
    "\25\0\4\7\u0116\6\2\0\6\6\2\0\46\6\2\0\6\6\2\0"+
    "\10\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6\2\0"+
    "\65\6\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6\3\0"+
    "\4\6\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6\16\0"+
    "\5\7\30\0\1\72\1\72\5\7\20\0\2\6\23\0\1\6\13\0"+
    "\5\7\5\0\6\7\1\0\1\6\15\0\1\6\20\0\15\6\3\0"+
    "\32\6\26\0\15\7\4\0\1\7\3\0\14\7\21\0\1\6\4\0"+
    "\1\6\2\0\12\6\1\0\1\6\3\0\5\6\6\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\4\6\1\0\13\6\2\0\4\6\5\0"+
    "\5\6\4\0\1\6\21\0\51\6\u0a77\0\57\6\1\0\57\6\1\0"+
    "\205\6\6\0\4\6\3\7\16\0\46\6\12\0\66\6\11\0\1\6"+
    "\17\0\1\7\27\6\11\0\7\6\1\0\7\6\1\0\7\6\1\0"+
    "\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0"+
    "\40\7\57\0\1\6\u01d5\0\3\6\31\0\11\6\6\7\1\0\5\6"+
    "\2\0\5\6\4\0\126\6\2\0\2\7\2\0\3\6\1\0\132\6"+
    "\1\0\4\6\5\0\51\6\3\0\136\6\21\0\33\6\65\0\20\6"+
    "\u0200\0\u19b6\6\112\0\u51cc\6\64\0\u048d\6\103\0\56\6\2\0\u010d\6"+
    "\3\0\20\6\12\7\2\6\24\0\57\6\1\7\14\0\2\7\1\0"+
    "\31\6\10\0\120\6\2\7\45\0\11\6\2\0\147\6\2\0\4\6"+
    "\1\0\2\6\16\0\12\6\120\0\10\6\1\7\3\6\1\7\4\6"+
    "\1\7\27\6\5\7\20\0\1\6\7\0\64\6\14\0\2\7\62\6"+
    "\21\7\13\0\12\7\6\0\22\7\6\6\3\0\1\6\4\0\12\7"+
    "\34\6\10\7\2\0\27\6\15\7\14\0\35\6\3\0\4\7\57\6"+
    "\16\7\16\0\1\6\12\7\46\0\51\6\16\7\11\0\3\6\1\7"+
    "\10\6\2\7\2\0\12\7\6\0\27\6\3\0\1\6\1\7\4\0"+
    "\60\6\1\7\1\6\3\7\2\6\2\7\5\6\2\7\1\6\1\7"+
    "\1\6\30\0\3\6\43\0\6\6\2\0\6\6\2\0\6\6\11\0"+
    "\7\6\1\0\7\6\221\0\43\6\10\7\1\0\2\7\2\0\12\7"+
    "\6\0\u2ba4\6\14\0\27\6\4\0\61\6\u2104\0\u012e\6\2\0\76\6"+
    "\2\0\152\6\46\0\7\6\14\0\5\6\5\0\1\6\1\7\12\6"+
    "\1\0\15\6\1\0\5\6\1\0\1\6\1\0\2\6\1\0\2\6"+
    "\1\0\154\6\41\0\u016b\6\22\0\100\6\2\0\66\6\50\0\15\6"+
    "\3\0\20\7\20\0\7\7\14\0\2\6\30\0\3\6\31\0\1\6"+
    "\6\0\5\6\1\0\207\6\2\0\1\7\4\0\1\6\13\0\12\7"+
    "\7\0\32\6\4\0\1\6\1\0\32\6\13\0\131\6\3\0\6\6"+
    "\2\0\6\6\2\0\6\6\2\0\3\6\3\0\2\6\3\0\2\6"+
    "\22\0\3\7\4\0\14\6\1\0\32\6\1\0\23\6\1\0\2\6"+
    "\1\0\17\6\2\0\16\6\42\0\173\6\105\0\65\6\210\0\1\7"+
    "\202\0\35\6\3\0\61\6\57\0\37\6\21\0\33\6\65\0\36\6"+
    "\2\0\44\6\4\0\10\6\1\0\5\6\52\0\236\6\2\0\12\7"+
    "\u0356\0\6\6\2\0\1\6\1\0\54\6\1\0\2\6\3\0\1\6"+
    "\2\0\27\6\252\0\26\6\12\0\32\6\306\0\1\6\3\7\1\0"+
    "\2\7\5\0\4\7\4\6\1\0\3\6\1\0\33\6\4\0\3\7"+
    "\4\0\1\7\40\0\35\6\203\0\66\6\12\0\26\6\12\0\23\6"+
    "\215\0\111\6\u03b7\0\3\7\65\6\17\7\37\0\12\7\20\0\3\7"+
    "\55\6\13\7\2\0\1\7\u0f42\0\u036f\6\221\0\143\6\u0b9d\0\u042f\6"+
    "\u33d1\0\u0239\6\u45c7\0\2\6\u2163\0\5\7\3\0\26\7\2\0\7\7"+
    "\36\0\4\7\224\0\3\7\u01bb\0\125\6\1\0\107\6\1\0\2\6"+
    "\2\0\1\6\2\0\2\6\2\0\4\6\1\0\14\6\1\0\1\6"+
    "\1\0\7\6\1\0\101\6\1\0\4\6\2\0\10\6\1\0\7\6"+
    "\1\0\34\6\1\0\4\6\1\0\5\6\1\0\1\6\3\0\7\6"+
    "\1\0\u0154\6\2\0\31\6\1\0\31\6\1\0\37\6\1\0\31\6"+
    "\1\0\37\6\1\0\31\6\1\0\37\6\1\0\31\6\1\0\37\6"+
    "\1\0\31\6\1\0\10\6\2\0\62\7\u2800\0\ua6d7\6\51\0\u1035\6"+
    "\13\0\336\6\u3fe2\0\u021e\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\7\36\0\140\7\200\0\360\7\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\1\11\1\12\14\5\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\1\1\32\1\33\1\34\2\35"+
    "\1\36\2\1\2\37\1\1\1\0\1\2\1\0\2\40"+
    "\1\0\1\41\22\5\1\42\6\5\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\11\0\1\40"+
    "\1\0\3\5\1\64\13\5\1\65\3\5\1\66\10\5"+
    "\1\67\1\70\1\71\1\72\1\73\1\74\1\75\1\76"+
    "\1\5\1\77\1\5\1\100\1\5\1\101\5\5\1\102"+
    "\1\5\1\103\14\5\1\104\2\5\1\105\3\5\1\106"+
    "\2\5\1\107\1\110\1\111\3\5\1\112\7\5\1\113"+
    "\1\114\4\5\1\115\4\5\1\116\1\5\1\117\1\120"+
    "\5\5\1\121\1\5\1\122\1\5\1\123\5\5\1\124"+
    "\1\5\1\125\1\126\1\5\1\127\1\5\1\130\1\5"+
    "\1\131";

  private static int [] zzUnpackAction() {
    int [] result = new int[240];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\364\0\267\0\u0131\0\267"+
    "\0\u016e\0\u01ab\0\u01e8\0\u0225\0\u0262\0\267\0\267\0\u029f"+
    "\0\u02dc\0\u0319\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487"+
    "\0\u04c4\0\u0501\0\u053e\0\267\0\267\0\267\0\267\0\267"+
    "\0\267\0\267\0\267\0\u057b\0\u05b8\0\u05f5\0\u0632\0\267"+
    "\0\267\0\u066f\0\u06ac\0\u06e9\0\267\0\u0726\0\u0763\0\267"+
    "\0\267\0\u07a0\0\u07dd\0\u081a\0\267\0\u0857\0\u07dd\0\u0894"+
    "\0\u08d1\0\u01ab\0\u090e\0\u094b\0\267\0\u0988\0\u09c5\0\u0a02"+
    "\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6\0\u0b33\0\u0b70\0\u0bad\0\u0bea"+
    "\0\u0c27\0\u0c64\0\u0ca1\0\u0cde\0\u0d1b\0\u0d58\0\u0d95\0\u016e"+
    "\0\u0dd2\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6\0\u0f03\0\267\0\267"+
    "\0\267\0\267\0\267\0\267\0\267\0\267\0\267\0\267"+
    "\0\267\0\267\0\267\0\267\0\267\0\267\0\267\0\u0f40"+
    "\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u10ae\0\u10eb\0\u1128"+
    "\0\u1165\0\u1165\0\u11a2\0\u11df\0\u121c\0\u016e\0\u1259\0\u1296"+
    "\0\u12d3\0\u1310\0\u134d\0\u138a\0\u13c7\0\u1404\0\u1441\0\u147e"+
    "\0\u14bb\0\u016e\0\u14f8\0\u1535\0\u1572\0\u15af\0\u15ec\0\u1629"+
    "\0\u1666\0\u16a3\0\u16e0\0\u171d\0\u175a\0\u1797\0\267\0\267"+
    "\0\267\0\267\0\267\0\267\0\267\0\267\0\u17d4\0\u016e"+
    "\0\u1811\0\u016e\0\u184e\0\u016e\0\u188b\0\u18c8\0\u1905\0\u1942"+
    "\0\u197f\0\u016e\0\u19bc\0\u016e\0\u19f9\0\u1a36\0\u1a73\0\u1ab0"+
    "\0\u1aed\0\u1b2a\0\u1b67\0\u1ba4\0\u1be1\0\u1c1e\0\u1c5b\0\u1c98"+
    "\0\u016e\0\u1cd5\0\u1d12\0\u016e\0\u1d4f\0\u1d8c\0\u1dc9\0\u016e"+
    "\0\u1e06\0\u1e43\0\u016e\0\u016e\0\u016e\0\u1e80\0\u1ebd\0\u1efa"+
    "\0\u016e\0\u1f37\0\u1f74\0\u1fb1\0\u1fee\0\u202b\0\u2068\0\u20a5"+
    "\0\u016e\0\u016e\0\u20e2\0\u211f\0\u215c\0\u2199\0\u016e\0\u21d6"+
    "\0\u2213\0\u2250\0\u228d\0\u016e\0\u22ca\0\u016e\0\u016e\0\u2307"+
    "\0\u2344\0\u2381\0\u23be\0\u23fb\0\u016e\0\u2438\0\u016e\0\u2475"+
    "\0\u016e\0\u24b2\0\u24ef\0\u252c\0\u2569\0\u25a6\0\u016e\0\u25e3"+
    "\0\u016e\0\u016e\0\u2620\0\u016e\0\u265d\0\u016e\0\u269a\0\u016e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[240];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\11\1\4\1\12"+
    "\1\13\1\14\1\11\1\15\1\16\1\17\1\4\1\20"+
    "\2\11\1\21\1\11\1\22\1\23\1\11\1\24\1\25"+
    "\1\11\1\26\1\11\1\27\1\30\1\31\1\32\3\11"+
    "\1\33\3\11\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\0\1\6\1\0\1\56"+
    "\1\57\1\60\12\56\1\61\1\56\1\62\55\56\1\63"+
    "\1\64\1\65\13\63\1\4\1\66\52\63\3\67\77\0"+
    "\1\6\76\0\1\70\1\71\75\0\4\11\1\0\1\11"+
    "\4\0\30\11\24\0\1\11\10\0\2\72\1\73\1\74"+
    "\7\0\1\74\61\0\2\13\1\73\1\74\7\0\1\74"+
    "\61\0\2\73\77\0\1\75\66\0\4\11\1\0\1\11"+
    "\4\0\1\11\1\76\26\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\2\11\1\77\7\11\1\100\15\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\3\11"+
    "\1\101\15\11\1\102\6\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\2\11\1\103\4\11\1\104\20\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\3\11"+
    "\1\105\24\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\13\11\1\106\5\11\1\107\1\110\5\11\24\0"+
    "\1\11\6\0\4\11\1\0\1\11\4\0\7\11\1\111"+
    "\1\112\17\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\1\11\1\113\1\114\1\11\1\115\11\11\1\116"+
    "\11\11\24\0\1\11\6\0\4\11\1\0\1\11\4\0"+
    "\5\11\1\117\7\11\1\120\11\11\1\121\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\7\11\1\122\20\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\4\11"+
    "\1\123\3\11\1\124\10\11\1\125\6\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\1\11\1\126\26\11"+
    "\24\0\1\11\60\0\1\127\74\0\1\130\74\0\1\131"+
    "\74\0\1\132\102\0\1\133\75\0\1\134\75\0\1\135"+
    "\4\0\1\56\2\0\12\56\1\0\1\56\1\0\55\56"+
    "\2\0\1\60\72\0\1\136\2\0\12\136\1\137\1\140"+
    "\1\141\1\142\4\136\1\143\2\136\1\144\2\136\1\145"+
    "\1\136\1\146\34\136\21\0\1\147\60\0\1\65\107\0"+
    "\1\150\1\151\1\152\1\153\4\0\1\154\2\0\1\155"+
    "\2\0\1\156\1\0\1\157\37\0\1\70\1\5\1\6"+
    "\72\70\5\71\1\160\67\71\10\0\2\73\1\0\1\74"+
    "\7\0\1\74\61\0\2\161\2\0\1\162\53\0\1\162"+
    "\12\0\4\11\1\0\1\11\4\0\1\11\1\163\26\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\11\11"+
    "\1\164\16\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\13\11\1\165\14\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\17\11\1\166\10\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\2\11\1\167\25\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\4\11"+
    "\1\170\23\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\4\11\1\171\23\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\13\11\1\172\14\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\4\11\1\173\3\11"+
    "\1\174\17\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\20\11\1\175\7\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\5\11\1\176\22\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\16\11\1\177\11\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\4\11"+
    "\1\200\14\11\1\201\6\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\10\11\1\202\17\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\1\11\1\203\26\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\2\11"+
    "\1\204\25\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\5\11\1\205\22\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\13\11\1\206\14\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\20\11\1\207\7\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\16\11"+
    "\1\210\11\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\6\11\1\211\21\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\1\11\1\212\14\11\1\213\11\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\1\214"+
    "\27\11\24\0\1\11\6\0\4\11\1\0\1\11\4\0"+
    "\2\11\1\215\13\11\1\216\11\11\24\0\1\11\16\0"+
    "\1\217\74\0\1\220\74\0\1\221\74\0\1\222\74\0"+
    "\1\223\74\0\1\224\74\0\1\225\74\0\1\226\56\0"+
    "\4\71\1\6\1\160\67\71\10\0\2\161\71\0\4\11"+
    "\1\0\1\11\4\0\2\11\1\227\25\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\3\11\1\230\24\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\3\11"+
    "\1\231\24\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\2\11\1\232\25\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\11\11\1\233\16\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\10\11\1\234\17\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\21\11"+
    "\1\235\6\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\13\11\1\236\14\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\16\11\1\237\11\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\3\11\1\240\24\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\6\11"+
    "\1\241\21\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\11\11\1\242\16\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\5\11\1\243\22\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\3\11\1\244\24\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\4\11"+
    "\1\245\23\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\11\11\1\246\16\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\4\11\1\247\23\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\3\11\1\250\24\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\1\11"+
    "\1\251\1\252\25\11\24\0\1\11\6\0\4\11\1\0"+
    "\1\11\4\0\2\11\1\253\25\11\24\0\1\11\6\0"+
    "\4\11\1\0\1\11\4\0\25\11\1\254\2\11\24\0"+
    "\1\11\6\0\4\11\1\0\1\11\4\0\13\11\1\255"+
    "\14\11\24\0\1\11\6\0\4\11\1\0\1\11\4\0"+
    "\24\11\1\256\3\11\24\0\1\11\6\0\4\11\1\0"+
    "\1\11\4\0\2\11\1\257\25\11\24\0\1\11\6\0"+
    "\4\11\1\0\1\11\4\0\4\11\1\260\23\11\24\0"+
    "\1\11\6\0\4\11\1\0\1\11\4\0\14\11\1\261"+
    "\13\11\24\0\1\11\6\0\4\11\1\0\1\11\4\0"+
    "\3\11\1\262\24\11\24\0\1\11\6\0\4\11\1\0"+
    "\1\11\4\0\5\11\1\263\22\11\24\0\1\11\6\0"+
    "\4\11\1\0\1\11\4\0\11\11\1\264\16\11\24\0"+
    "\1\11\6\0\4\11\1\0\1\11\4\0\10\11\1\265"+
    "\17\11\24\0\1\11\6\0\4\11\1\0\1\11\4\0"+
    "\16\11\1\266\11\11\24\0\1\11\6\0\4\11\1\0"+
    "\1\11\4\0\6\11\1\267\21\11\24\0\1\11\6\0"+
    "\4\11\1\0\1\11\4\0\10\11\1\270\17\11\24\0"+
    "\1\11\6\0\4\11\1\0\1\11\4\0\7\11\1\271"+
    "\20\11\24\0\1\11\6\0\4\11\1\0\1\11\4\0"+
    "\11\11\1\272\16\11\24\0\1\11\6\0\4\11\1\0"+
    "\1\11\4\0\13\11\1\273\14\11\24\0\1\11\6\0"+
    "\4\11\1\0\1\11\4\0\3\11\1\274\24\11\24\0"+
    "\1\11\6\0\4\11\1\0\1\11\4\0\2\11\1\275"+
    "\25\11\24\0\1\11\6\0\4\11\1\0\1\11\4\0"+
    "\10\11\1\276\17\11\24\0\1\11\6\0\4\11\1\0"+
    "\1\11\4\0\10\11\1\277\17\11\24\0\1\11\6\0"+
    "\4\11\1\0\1\11\4\0\3\11\1\300\24\11\24\0"+
    "\1\11\6\0\4\11\1\0\1\11\4\0\3\11\1\301"+
    "\24\11\24\0\1\11\6\0\4\11\1\0\1\11\4\0"+
    "\4\11\1\302\23\11\24\0\1\11\6\0\4\11\1\0"+
    "\1\11\4\0\3\11\1\303\24\11\24\0\1\11\6\0"+
    "\4\11\1\0\1\11\4\0\4\11\1\304\23\11\24\0"+
    "\1\11\6\0\4\11\1\0\1\11\4\0\16\11\1\305"+
    "\11\11\24\0\1\11\6\0\4\11\1\0\1\11\4\0"+
    "\13\11\1\306\14\11\24\0\1\11\6\0\4\11\1\0"+
    "\1\11\4\0\4\11\1\307\23\11\24\0\1\11\6\0"+
    "\4\11\1\0\1\11\4\0\14\11\1\310\13\11\24\0"+
    "\1\11\6\0\4\11\1\0\1\11\4\0\5\11\1\311"+
    "\22\11\24\0\1\11\6\0\4\11\1\0\1\11\4\0"+
    "\6\11\1\312\21\11\24\0\1\11\6\0\4\11\1\0"+
    "\1\11\4\0\13\11\1\313\14\11\24\0\1\11\6\0"+
    "\4\11\1\0\1\11\4\0\10\11\1\314\17\11\24\0"+
    "\1\11\6\0\4\11\1\0\1\11\4\0\16\11\1\315"+
    "\11\11\24\0\1\11\6\0\4\11\1\0\1\11\4\0"+
    "\15\11\1\316\12\11\24\0\1\11\6\0\4\11\1\0"+
    "\1\11\4\0\13\11\1\317\14\11\24\0\1\11\6\0"+
    "\4\11\1\0\1\11\4\0\27\11\1\320\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\26\11\1\321\1\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\6\11"+
    "\1\322\21\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\13\11\1\323\14\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\6\11\1\324\21\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\16\11\1\325\11\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\5\11"+
    "\1\326\22\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\11\11\1\327\16\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\15\11\1\330\12\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\1\11\1\331\26\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\3\11"+
    "\1\332\24\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\4\11\1\333\23\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\3\11\1\334\24\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\3\11\1\335\24\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\13\11"+
    "\1\336\14\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\3\11\1\337\24\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\2\11\1\340\25\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\20\11\1\341\7\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\5\11"+
    "\1\342\22\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\5\11\1\343\22\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\6\11\1\344\21\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\5\11\1\345\22\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\3\11"+
    "\1\346\24\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\3\11\1\347\24\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\16\11\1\350\11\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\13\11\1\351\14\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\3\11"+
    "\1\352\24\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\13\11\1\353\14\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\14\11\1\354\13\11\24\0\1\11"+
    "\6\0\4\11\1\0\1\11\4\0\23\11\1\355\4\11"+
    "\24\0\1\11\6\0\4\11\1\0\1\11\4\0\11\11"+
    "\1\356\16\11\24\0\1\11\6\0\4\11\1\0\1\11"+
    "\4\0\3\11\1\357\24\11\24\0\1\11\6\0\4\11"+
    "\1\0\1\11\4\0\14\11\1\360\13\11\24\0\1\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9943];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\1\1\1\11\5\1\2\11"+
    "\14\1\10\11\4\1\2\11\3\1\1\11\2\1\2\11"+
    "\3\1\1\11\1\1\1\0\1\1\1\0\2\1\1\0"+
    "\1\11\31\1\21\11\11\0\1\1\1\0\34\1\10\11"+
    "\132\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[240];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuffer string = new StringBuffer();
  
  private Symbol symbol(int type) {
    return new JavaSymbol(type, yyline+1, yycolumn+1, yytext());
  }

  private Symbol symbol(int type, Object value) {
    return new JavaSymbol(type, yyline+1, yycolumn+1, yytext(), value);
  }

  public String current_lexeme(){
    int l = yyline+1;
    int c = yycolumn+1;
    return " (line: "+l+" , column: "+c+" , lexeme: '"+yytext()+"')";
  }

  /** 
   * assumes correct representation of a long value for 
   * specified radix in scanner buffer from <code>start</code> 
   * to <code>end</code> 
   */
  private long parseLong(int start, int end, int radix) {
    long result = 0;
    long digit;

    for (int i = start; i < end; i++) {
      digit  = Character.digit(yycharat(i),radix);
      result*= radix;
      result+= digit;
    }

    return result;
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2628) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return symbol(sym.ILLEGAL_CHARACTER, yytext());
          }
        case 90: break;
        case 2: 
          { /* ignore */
          }
        case 91: break;
        case 3: 
          { return symbol(sym.DIV);
          }
        case 92: break;
        case 4: 
          { return symbol(sym.MULT);
          }
        case 93: break;
        case 5: 
          { return symbol(sym.IDENTIFIER, yytext());
          }
        case 94: break;
        case 6: 
          { return symbol(sym.INTEGER_LITERAL, new Integer(yytext()));
          }
        case 95: break;
        case 7: 
          { return symbol(sym.DOT);
          }
        case 96: break;
        case 8: 
          { return symbol(sym.PLUS);
          }
        case 97: break;
        case 9: 
          { yybegin(STRING); string.setLength(0);
          }
        case 98: break;
        case 10: 
          { yybegin(CHARLITERAL);
          }
        case 99: break;
        case 11: 
          { return symbol(sym.LPAREN);
          }
        case 100: break;
        case 12: 
          { return symbol(sym.RPAREN);
          }
        case 101: break;
        case 13: 
          { return symbol(sym.LBRACE);
          }
        case 102: break;
        case 14: 
          { return symbol(sym.RBRACE);
          }
        case 103: break;
        case 15: 
          { return symbol(sym.LBRACK);
          }
        case 104: break;
        case 16: 
          { return symbol(sym.RBRACK);
          }
        case 105: break;
        case 17: 
          { return symbol(sym.SEMICOLON);
          }
        case 106: break;
        case 18: 
          { return symbol(sym.COMMA);
          }
        case 107: break;
        case 19: 
          { return symbol(sym.EQ);
          }
        case 108: break;
        case 20: 
          { return symbol(sym.GT);
          }
        case 109: break;
        case 21: 
          { return symbol(sym.LT);
          }
        case 110: break;
        case 22: 
          { return symbol(sym.NOT);
          }
        case 111: break;
        case 23: 
          { return symbol(sym.QUESTION);
          }
        case 112: break;
        case 24: 
          { return symbol(sym.COLON);
          }
        case 113: break;
        case 25: 
          { return symbol(sym.AT);
          }
        case 114: break;
        case 26: 
          { return symbol(sym.MINUS);
          }
        case 115: break;
        case 27: 
          { return symbol(sym.MOD);
          }
        case 116: break;
        case 28: 
          { string.append( yytext() );
          }
        case 117: break;
        case 29: 
          { throw new RuntimeException("Unterminated string at end of line");
          }
        case 118: break;
        case 30: 
          { yybegin(YYINITIAL); return symbol(sym.STRING_LITERAL, string.toString());
          }
        case 119: break;
        case 31: 
          { throw new RuntimeException("Unterminated character literal at end of line");
          }
        case 120: break;
        case 32: 
          { return symbol(sym.FLOATING_POINT_LITERAL, new Float(yytext().substring(0,yylength())));
          }
        case 121: break;
        case 33: 
          { return symbol(sym.PLUSPLUS);
          }
        case 122: break;
        case 34: 
          { return symbol(sym.IF);
          }
        case 123: break;
        case 35: 
          { return symbol(sym.EQEQ);
          }
        case 124: break;
        case 36: 
          { return symbol(sym.GTEQ);
          }
        case 125: break;
        case 37: 
          { return symbol(sym.LTEQ);
          }
        case 126: break;
        case 38: 
          { return symbol(sym.NOTEQ);
          }
        case 127: break;
        case 39: 
          { return symbol(sym.ANDAND);
          }
        case 128: break;
        case 40: 
          { return symbol(sym.OROR);
          }
        case 129: break;
        case 41: 
          { return symbol(sym.MINUSMINUS);
          }
        case 130: break;
        case 42: 
          { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
          }
        case 131: break;
        case 43: 
          { string.append( '\"' );
          }
        case 132: break;
        case 44: 
          { string.append( '\'' );
          }
        case 133: break;
        case 45: 
          { string.append( '\\' );
          }
        case 134: break;
        case 46: 
          { string.append( '\b' );
          }
        case 135: break;
        case 47: 
          { string.append( '\n' );
          }
        case 136: break;
        case 48: 
          { string.append( '\r' );
          }
        case 137: break;
        case 49: 
          { string.append( '\t' );
          }
        case 138: break;
        case 50: 
          { string.append( '\f' );
          }
        case 139: break;
        case 51: 
          { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, new Character(yytext().charAt(0)));
          }
        case 140: break;
        case 52: 
          { return symbol(sym.NEW);
          }
        case 141: break;
        case 53: 
          { return symbol(sym.FOR);
          }
        case 142: break;
        case 54: 
          { return symbol(sym.INT);
          }
        case 143: break;
        case 55: 
          { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, new Character('\"'));
          }
        case 144: break;
        case 56: 
          { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, new Character('\''));
          }
        case 145: break;
        case 57: 
          { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, new Character('\\'));
          }
        case 146: break;
        case 58: 
          { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, new Character('\b'));
          }
        case 147: break;
        case 59: 
          { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, new Character('\n'));
          }
        case 148: break;
        case 60: 
          { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, new Character('\r'));
          }
        case 149: break;
        case 61: 
          { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, new Character('\t'));
          }
        case 150: break;
        case 62: 
          { yybegin(YYINITIAL); return symbol(sym.CHARACTER_LITERAL, new Character('\f'));
          }
        case 151: break;
        case 63: 
          { return symbol(sym.ELSE);
          }
        case 152: break;
        case 64: 
          { return symbol(sym.NULL_LITERAL);
          }
        case 153: break;
        case 65: 
          { return symbol(sym.CHAR);
          }
        case 154: break;
        case 66: 
          { return symbol(sym.THIS);
          }
        case 155: break;
        case 67: 
          { return symbol(sym.BOOLEAN_LITERAL, new Boolean(true));
          }
        case 156: break;
        case 68: 
          { return symbol( sym.VOID);
          }
        case 157: break;
        case 69: 
          { return symbol(sym.CLASS);
          }
        case 158: break;
        case 70: 
          { return symbol( sym.SUPER);
          }
        case 159: break;
        case 71: 
          { return symbol(sym.FLOAT);
          }
        case 160: break;
        case 72: 
          { return symbol(sym.BOOLEAN_LITERAL, new Boolean(false));
          }
        case 161: break;
        case 73: 
          { return symbol( sym.FINAL);
          }
        case 162: break;
        case 74: 
          { return symbol(sym.WHILE);
          }
        case 163: break;
        case 75: 
          { return symbol( sym.RETURN);
          }
        case 164: break;
        case 76: 
          { return symbol( sym.STATIC);
          }
        case 165: break;
        case 77: 
          { return symbol( sym.IMPORT);
          }
        case 166: break;
        case 78: 
          { return symbol( sym.PUBLIC);
          }
        case 167: break;
        case 79: 
          { return symbol(sym.BOOLEAN);
          }
        case 168: break;
        case 80: 
          { return symbol(sym.EXTENDS);
          }
        case 169: break;
        case 81: 
          { return symbol( sym.PACKAGE);
          }
        case 170: break;
        case 82: 
          { return symbol( sym.PRIVATE);
          }
        case 171: break;
        case 83: 
          { return symbol( sym.STRICTFP);
          }
        case 172: break;
        case 84: 
          { return symbol( sym.VOLATILE);
          }
        case 173: break;
        case 85: 
          { return symbol( sym.TRANSIENT);
          }
        case 174: break;
        case 86: 
          { return symbol( sym.INTERFACE);
          }
        case 175: break;
        case 87: 
          { return symbol( sym.PROTECTED);
          }
        case 176: break;
        case 88: 
          { return symbol( sym.IMPLEMENTS);
          }
        case 177: break;
        case 89: 
          { return symbol( sym.SYNCHRONIZED);
          }
        case 178: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Scanner [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Scanner(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
