
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jul 12 22:46:05 BRT 2015
//----------------------------------------------------

package jflexcup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 59;
  public static final int GTEQ = 48;
  public static final int MULT = 10;
  public static final int CHAR = 4;
  public static final int LTEQ = 47;
  public static final int STRICTFP = 28;
  public static final int LPAREN = 15;
  public static final int PRIVATE = 20;
  public static final int INT = 3;
  public static final int MINUS = 41;
  public static final int STATIC = 21;
  public static final int RPAREN = 16;
  public static final int BOOLEAN_LITERAL = 57;
  public static final int OROR = 52;
  public static final int CHARACTER_LITERAL = 58;
  public static final int NOT = 42;
  public static final int SEMICOLON = 9;
  public static final int LT = 45;
  public static final int ILLEGAL_CHARACTER = 54;
  public static final int COMMA = 11;
  public static final int CLASS = 29;
  public static final int ANDAND = 51;
  public static final int DIV = 43;
  public static final int PLUS = 40;
  public static final int NULL_LITERAL = 61;
  public static final int IF = 35;
  public static final int THIS = 32;
  public static final int DOT = 8;
  public static final int ABSTRACT = 22;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 38;
  public static final int NEW = 39;
  public static final int SUPER = 33;
  public static final int error = 1;
  public static final int TRANSIENT = 26;
  public static final int EQEQ = 49;
  public static final int MOD = 44;
  public static final int VOID = 31;
  public static final int EQ = 14;
  public static final int LBRACK = 6;
  public static final int COLON = 17;
  public static final int FLOATING_POINT_LITERAL = 56;
  public static final int ELSE = 36;
  public static final int LBRACE = 12;
  public static final int NATIVE = 24;
  public static final int PROTECTED = 19;
  public static final int RBRACK = 7;
  public static final int WHILE = 37;
  public static final int FINAL = 23;
  public static final int FLOAT = 5;
  public static final int PUBLIC = 18;
  public static final int RBRACE = 13;
  public static final int EXTENDS = 30;
  public static final int QUESTION = 53;
  public static final int VOLATILE = 27;
  public static final int SYNCHRONIZED = 25;
  public static final int AT = 34;
  public static final int GT = 46;
  public static final int NOTEQ = 50;
  public static final int IDENTIFIER = 60;
  public static final int INTEGER_LITERAL = 55;
}

